// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmmQl7iCb-HA5URxb8VfP1CWDoZznfBE8',
    appId: '1:32186681146:web:e262feaf1cb05f194a3203',
    messagingSenderId: '32186681146',
    projectId: 'foreachmaxime-3fcc4',
    authDomain: 'foreachmaxime-3fcc4.firebaseapp.com',
    databaseURL: 'https://foreachmaxime-3fcc4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'foreachmaxime-3fcc4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsos57I35n-fdcJ0sLUCUYbuUNP_1wNhI',
    appId: '1:32186681146:android:9ab9b35d0e1ce9d04a3203',
    messagingSenderId: '32186681146',
    projectId: 'foreachmaxime-3fcc4',
    databaseURL: 'https://foreachmaxime-3fcc4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'foreachmaxime-3fcc4.appspot.com',
  );
}
